-- tabla bloque
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('A', 5);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('B', 8);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('C', 10);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('D', 6);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('E', 12);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('F', 7);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('G', 9);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('H', 11);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('I', 8);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('Area Amarilla', 6);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('Area Azul', 10);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('Area Blanca', 9);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('Area Gris', 8);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('Area Morada', 7);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('Area Naranja', 12);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('Area Negra', 11);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('Area Roja', 5);
INSERT INTO public.bloque (nombre, nro_piso) VALUES ('Area Rosada', 4);

-- tabla empresa
INSERT INTO public.empresa (logo, nombre) VALUES ('https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Apple_logo_grey.svg/1724px-Apple_logo_grey.svg.png', 'Apple');
INSERT INTO public.empresa (logo, nombre) VALUES ('https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/2048px-Microsoft_logo.svg.png', 'Microsoft');
INSERT INTO public.empresa (logo, nombre) VALUES ('https://i.pinimg.com/originals/01/ca/da/01cada77a0a7d326d85b7969fe26a728.jpg', 'Amazon');
INSERT INTO public.empresa (logo, nombre) VALUES ('https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Tesla_Motors.svg/793px-Tesla_Motors.svg.png', 'Tesla');
INSERT INTO public.empresa (logo, nombre) VALUES ('https://rotulosmatesanz.com/wp-content/uploads/2017/09/2000px-Google_G_Logo.svg_.png', 'Google');
INSERT INTO public.empresa (logo, nombre) VALUES ('https://tja.ucb.edu.bo/wp-content/uploads/2020/09/cropped-logo-UCB.png?w=640', 'Universidad Catolica');

-- tabla bloque_empresa
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (1, 6);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (2, 6);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (3, 6);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (4, 6);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (5, 6);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (6, 6);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (7, 6);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (8, 6);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (9, 6);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (10, 2);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (11, 2);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (12, 2);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (13, 2);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (14, 2);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (15, 2);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (16, 2);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (17, 2);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (18, 2);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (1, 4);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (2, 4);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (3, 4);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (4, 4);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (5, 4);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (6, 4);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (7, 4);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (8, 4);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (9, 4);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (10, 5);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (11, 5);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (12, 5);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (13, 5);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (14, 5);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (15, 5);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (16, 5);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (17, 5);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (18, 5);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (1, 1);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (2, 1);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (3, 1);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (4, 1);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (5, 1);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (6, 1);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (7, 1);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (8, 1);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (9, 1);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (10, 3);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (11, 3);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (12, 3);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (13, 3);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (14, 3);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (15, 3);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (16, 3);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (17, 3);
INSERT INTO public.bloque_empresa (bloque_id, empresa_id) VALUES (18, 3);

-- tabla oficina
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación 1', 'Oficina 100');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación 2', 'Oficina 101');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación 3', 'Oficina 102');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación 4', 'Oficina 103');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación 5', 'Oficina 104');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación 6', 'Oficina 105');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación 7', 'Oficina 106');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación 8', 'Oficina 107');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación 9', 'Oficina 108');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación 10', 'Oficina 109');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 1', 'Aula B1');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 10', 'Aula B10');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 2', 'Aula B2');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 3', 'Aula B3');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 4', 'Aula B4');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 5', 'Aula B5');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 6', 'Aula B6');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 7', 'Aula B7');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 8', 'Aula B8');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 9', 'Aula B9');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 1', 'Aula C1');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 10', 'Aula C10');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 2', 'Aula C2');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 3', 'Aula C3');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 4', 'Aula C4');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 5', 'Aula C5');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 6', 'Aula C6');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 7', 'Aula C7');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 8', 'Aula C8');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 9', 'Aula C9');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 1', 'Aula D1');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 10', 'Aula D10');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 2', 'Aula D2');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 3', 'Aula D3');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 4', 'Aula D4');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 5', 'Aula D5');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 6', 'Aula D6');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 7', 'Aula D7');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 8', 'Aula D8');
INSERT INTO public.oficina (descripcion, nombre) VALUES ('Ubicación Aula 9', 'Aula D9');

-- tabla oficina_empresa
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 11);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 12);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 13);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 14);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 15);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 16);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 17);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 18);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 19);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 20);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 21);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 22);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 23);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 24);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 25);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 26);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 27);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 28);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 29);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 30);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 31);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 32);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 33);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 34);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 35);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 36);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 37);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 38);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 39);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (6, 40);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 11);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 12);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 13);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 14);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 15);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 16);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 17);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 18);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 19);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 20);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 21);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 22);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 23);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 24);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 25);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 26);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 27);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 28);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 29);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 30);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 31);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 32);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 33);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 34);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 35);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 36);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 37);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 38);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 39);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (4, 40);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 11);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 12);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 13);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 14);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 15);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 16);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 17);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 18);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 19);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 20);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 21);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 22);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 23);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 24);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 25);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 26);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 27);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 28);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 29);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 30);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 31);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 32);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 33);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 34);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 35);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 36);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 37);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 38);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 39);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (1, 40);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (2, 1);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (2, 2);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (2, 3);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (2, 4);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (2, 5);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (2, 6);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (2, 7);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (2, 8);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (2, 9);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (2, 10);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (5, 1);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (5, 2);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (5, 3);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (5, 4);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (5, 5);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (5, 6);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (5, 7);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (5, 8);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (5, 9);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (5, 10);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (3, 1);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (3, 2);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (3, 3);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (3, 4);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (3, 5);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (3, 6);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (3, 7);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (3, 8);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (3, 9);
INSERT INTO public.oficina_empresa (empresa_id, oficina_id) VALUES (3, 10);

-- tabla departamento
INSERT INTO public.departamento (nombre) VALUES ('La Paz');
INSERT INTO public.departamento (nombre) VALUES ('Beni');
INSERT INTO public.departamento (nombre) VALUES ('Pando');
INSERT INTO public.departamento (nombre) VALUES ('Oruro');
INSERT INTO public.departamento (nombre) VALUES ('Cochabamba');
INSERT INTO public.departamento (nombre) VALUES ('Santa Cruz');
INSERT INTO public.departamento (nombre) VALUES ('Sucre');
INSERT INTO public.departamento (nombre) VALUES ('Potosi');
INSERT INTO public.departamento (nombre) VALUES ('Tarija');

-- tabla ciudad
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('La Paz', 1);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('El Alto', 1);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('Oruro', 4);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('Cochabamba', 5);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('Santa Cruz de la Sierra', 6);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('Sucre', 7);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('Tarija', 9);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('Potosi', 8);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('Sacaba', 5);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('Quillacollo', 5);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('Trinidad', 2);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('Montero', 6);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('Warnes', 6);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('Riberalta', 2);
INSERT INTO public.ciudad (nombre, departamento_id) VALUES ('La Gaurdia', 6);

-- tabla ciudad_empresa
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (1, 1);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (2, 2);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (3, 1);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (4, 2);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (5, 3);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (6, 4);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (7, 3);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (8, 4);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (9, 5);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (10, 6);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (11, 5);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (12, 6);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (13, 1);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (14, 2);
INSERT INTO public.ciudad_empresa (ciudad_id, empresa_id) VALUES (15, 6);

-- tabla marca
INSERT INTO public.marca (nombre) VALUES ('Nike');
INSERT INTO public.marca (nombre) VALUES ('Adidas');
INSERT INTO public.marca (nombre) VALUES ('Apple');
INSERT INTO public.marca (nombre) VALUES ('Samsung');
INSERT INTO public.marca (nombre) VALUES ('Coca-Cola');
INSERT INTO public.marca (nombre) VALUES ('Toyota');
INSERT INTO public.marca (nombre) VALUES ('Microsoft');
INSERT INTO public.marca (nombre) VALUES ('Google');
INSERT INTO public.marca (nombre) VALUES ('Sony');
INSERT INTO public.marca (nombre) VALUES ('Puma');
INSERT INTO public.marca (nombre) VALUES ('Dacor');
INSERT INTO public.marca (nombre) VALUES ('Toshiba');
INSERT INTO public.marca (nombre) VALUES ('Sharp');
INSERT INTO public.marca (nombre) VALUES ('Sanyo');
INSERT INTO public.marca (nombre) VALUES ('Maytag');
INSERT INTO public.marca (nombre) VALUES ('Jenn-Air');
INSERT INTO public.marca (nombre) VALUES ('KitchenAid');
INSERT INTO public.marca (nombre) VALUES ('Nestle');
INSERT INTO public.marca (nombre) VALUES ('Honeywell');
INSERT INTO public.marca (nombre) VALUES ('Philips');

-- tabla personal
INSERT INTO public.personal (celular, ci, nombre) VALUES (555555555, '12345', 'Juan Pérez');
INSERT INTO public.personal (celular, ci, nombre) VALUES (666666666, '67890', 'María González');
INSERT INTO public.personal (celular, ci, nombre) VALUES (777777777, '54321', 'Pedro Ramírez');
INSERT INTO public.personal (celular, ci, nombre) VALUES (888888888, '98765', 'Luisa Fernández');
INSERT INTO public.personal (celular, ci, nombre) VALUES (999999999, '24680', 'Carlos Sánchez');
INSERT INTO public.personal (celular, ci, nombre) VALUES (69289005, '123456789', 'Laura Gómez');
INSERT INTO public.personal (celular, ci, nombre) VALUES (71534960, '987654321', 'Santiago López');
INSERT INTO public.personal (celular, ci, nombre) VALUES (69289123, '234567890', 'Isabel Pérez');
INSERT INTO public.personal (celular, ci, nombre) VALUES (71535000, '876543210', 'Martín Rodríguez');
INSERT INTO public.personal (celular, ci, nombre) VALUES (69289234, '345678901', 'Luisa Martínez');
INSERT INTO public.personal (celular, ci, nombre) VALUES (71537333, '876543210', 'Felipe González');
INSERT INTO public.personal (celular, ci, nombre) VALUES (69281456, '987654321', 'Florencia Silva');
INSERT INTO public.personal (celular, ci, nombre) VALUES (71537222, '108765432', 'Camilo Navarro');
INSERT INTO public.personal (celular, ci, nombre) VALUES (69281345, '219876543', 'Nicolás Díaz');
INSERT INTO public.personal (celular, ci, nombre) VALUES (71537111, '321098765', 'Martina Torres');
INSERT INTO public.personal (celular, ci, nombre) VALUES (69281234, '432109876', 'Sebastián Ortiz');
INSERT INTO public.personal (celular, ci, nombre) VALUES (71537000, '543210987', 'Abril Castro');
INSERT INTO public.personal (celular, ci, nombre) VALUES (69281123, '654321098', 'Isaac Martínez');
INSERT INTO public.personal (celular, ci, nombre) VALUES (71536999, '765432109', 'Francisco Soto');
INSERT INTO public.personal (celular, ci, nombre) VALUES (69281012, '876543210', 'Elena Ramírez');

-- tabla personal_empresa
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (1, 1);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (1, 3);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (1, 3);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (1, 4);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (1, 5);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (1, 6);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (1, 7);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (1, 8);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (1, 9);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (1, 10);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (2, 11);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (2, 12);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (2, 13);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (2, 14);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (2, 15);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (2, 16);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (2, 17);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (2, 18);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (2, 19);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (2, 20);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (3, 1);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (3, 3);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (3, 3);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (3, 4);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (3, 5);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (3, 6);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (3, 7);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (3, 8);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (3, 9);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (3, 10);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (4, 11);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (4, 12);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (4, 13);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (4, 14);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (4, 15);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (4, 16);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (4, 17);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (4, 18);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (4, 19);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (4, 20);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (5, 1);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (5, 3);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (5, 3);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (5, 4);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (5, 5);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (5, 6);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (5, 7);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (5, 8);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (5, 9);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (5, 10);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (6, 11);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (6, 12);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (6, 13);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (6, 14);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (6, 15);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (6, 16);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (6, 17);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (6, 18);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (6, 19);
INSERT INTO public.personal_empresa (empresa_id, personal_id) VALUES (6, 20);

-- tabla condicion
INSERT INTO public.condicion (nombre) VALUES ('Mal estado');
INSERT INTO public.condicion (nombre) VALUES ('Buen estado');
INSERT INTO public.condicion (nombre) VALUES ('Nuevo');
INSERT INTO public.condicion (nombre) VALUES ('Estado aceptable');

-- tabla rol
INSERT INTO public.rol (rol) VALUES ('Poweruser');
INSERT INTO public.rol (rol) VALUES ('Usuario');
INSERT INTO public.rol (rol) VALUES ('Administrador de Activos');
INSERT INTO public.rol (rol) VALUES ('Encargado de Depreciacion');

-- tabla tipo_activo
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Edificaciones', 3, 40);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Muebles y enseres de oficina', 10, 10);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Maquinaria en general', 13, 8);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Equipos e instalaciones', 13, 8);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Barcos y lanchas en general', 10, 10);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Vehículos automotores', 20, 5);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Aviones', 20, 5);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Maquinaria para la construcción', 20, 5);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Maquinaria agrícola', 25, 4);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Animales de trabajo', 25, 4);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Herramientas en general', 25, 4);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Reproductores y hembras pedigree o puros por cruza', 13,8);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Equipos de computación', 25, 4);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Canales de regadío y pozos', 5, 20);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Estanques, bañaderos y abrevaderos', 10, 10);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Alambrados, tranqueras y vallas', 10, 10);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Viviendas para el personal', 5, 20);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Muebles y enseres en las viviendas para el personal', 10, 10);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Silos, almacenes y galpones', 5, 20);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Tinglados y cobertizos de madera', 20, 5);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Tinglados y cobertizos de metal', 10, 10);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Ductos de la industria petrolera', 10, 10);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Plantas de Procesamiento de Industria Petrolera', 13, 8);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Equipos de campo de la industria Petrolera', 13, 8);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Líneas de Recolección de la industria Petrolera', 20, 5);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Pozos Petroleros', 20, 5);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Frutales', 10, 10);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Vides', 13, 8);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Caña de azúcar', 20, 5);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Caminos interiores', 10, 10);
INSERT INTO public.tipo_activo (nombre, porcentaje_depreciacion, vida_util) VALUES ('Instalaciones de electrificación y Telefonía rural', 10, 10);

-- tabla ubicacion
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Calle 5 de Mayo', 1, 'Avenida Reforma', 10);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Avenida Hidalgo', 2, 'Calle Juárez', 15);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Calle Madero', 3, 'Avenida Insurgentes', 10);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Avenida Benito Juárez', 4, 'Calle Guerrero', 15);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Calle Zaragoza', 5, 'Avenida Revolución', 10);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Avenida Morelos', 6, 'Calle Allende', 15);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Calle Colón', 7, 'Avenida Constitución', 10);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Avenida Carranza', 8, 'Calle Bravo', 15);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Calle Guzmán', 9, 'Avenida Guadalupe', 10);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Avenida Ávila Camacho', 10, 'Calle Rosales', 2);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Hernando Siles', 11, 'demetrio canelas', 4);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Calle Urbina', 12, 'Avenida Chavarría', 14);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Avenida Casares', 13, 'Calle Pacheco', 2);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Calle Corral', 14, 'Avenida Sáenz', 4);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Avenida Basurto', 15, 'Calle Barajas', 14);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Calle Gallegos', 16, 'Avenida Barrón', 2);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Avenida Gallardo', 17, 'Calle Hurtado', 4);
INSERT INTO public.ubicacion (avenida, bloque_id, calle, ciudad_id) VALUES ('Calle Niebla', 18, 'Avenida Armendáriz', 14);


-- tabla usuario
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (1, 'Ana Gómez', 'contrasena123', 'ana.gomez', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (2, 'Carlos Rodríguez', 'clave456', 'carlos.rodriguez', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (3, 'María Pérez', 'password789', 'maria.perez', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (4, 'Juan Martínez', 'secretoABC', 'juan.martinez', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (1, 'Laura Sánchez', 'clave123', 'laura.sanchez', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (2, 'Miguel López', 'password456', 'miguel.lopez', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (3, 'Sofía Ramírez', 'secreto789', 'sofia.ramirez', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (4, 'Pedro García', 'claveABC', 'pedro.garcia', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (1, 'Isabel Torres', 'password123', 'isabel.torres', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (2, 'Javier Vargas', 'secreto456', 'javier.vargas', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (3, 'geraldine ibieta', '1906', 'nini.ibieta', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (4, 'Eduardo Castro', 'claveABC', 'eduardo.castro', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (1, 'Paola Mendoza', 'secreto65', 'paola.mendoza', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (2, 'Martín González', 'password456', 'martin.gonzalez', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (3, 'Lucía Ramírez', 'clave123', 'lucia.ramirez', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (4, 'José Ortiz', 'secretoABC', 'jose.ortiz', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (1, 'Camila Guzmán', 'password789', 'camila.guzman', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (2, 'Arturo Vargas', 'clave456', 'arturo.vargas', true);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (3, 'Fernanda López', 'secreto123', 'fernanda.lopez', false);
INSERT INTO public.usuario (id_rol, nombre, password, username, status) VALUES (4, 'Emilio Medina', 'passwordABC', 'emilio.medina', true);

--tabla usuario_empresa
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (1, 1);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (1, 2);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (1, 3);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (1, 4);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (2, 5);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (2, 6);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (2, 7);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (2, 8);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (3, 9);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (3, 10);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (3, 11);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (3, 12);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (4, 13);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (4, 14);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (4, 15);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (4, 16);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (5, 17);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (5, 18);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (5, 19);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (5, 20);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (6, 1);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (6, 12);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (6, 13);
INSERT INTO public.usuario_empresa (empresa_id, usuario_id) VALUES (6, 2);


-- tabla activo_fijo
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Teléfono móvil', 1, true, 1, '2023-04-05 11:45:00.000000', '2023-04-05 12:00:00.000000', 1, 'Teléfono XYZ', 1, 1, 1, 600.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Monitor de pantalla plana', 1, true, 2, '2023-08-14 09:15:00.000000', '2023-10-14 09:30:00.000000', 2, 'Monitor LED', 2, 2, 2, 400.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Cámara digital', 1, true, 3, '2023-08-18 13:45:00.000000', '2023-08-18 14:00:00.000000', 3, 'Cámara DSLR', 3, 3, 3, 700.25);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Computadora portátil', 1, true, 4, '2023-01-15 10:30:00.000000', '2023-01-15 10:45:00.000000', 4, 'Laptop XYZ', 4, 4, 4, 1200.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Proyector multimedia', 1, true, 5, '2023-06-08 15:20:00.000000', '2023-06-08 15:35:00.000000', 5, 'Proyector HD', 5, 5, 5, 900.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Impresora láser', 1, true, 6, '2023-02-20 14:15:00.000000', '2023-02-20 14:30:00.000000', 6, 'Impresora ABC', 6, 6, 6, 800.75);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Escritorio ejecutivo', 1, true, 7, '2023-07-20 10:00:00.000000', '2023-07-20 10:15:00.000000', 7, 'Escritorio Ejecutivo', 7, 7, 7, 350.75);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Silla de oficina', 1, true, 8, '2023-05-12 08:30:00.000000', '2023-05-12 08:45:00.000000', 8, 'Silla Ergonómica', 8, 8, 8, 150.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Aire acondicionado', 1, true, 9, '2023-09-25 12:30:00.000000', '2023-09-25 12:45:00.000000', 9, 'Aire Acondicionado XYZ', 9, 9, 9, 1200.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Mesa de oficina', 1, true, 10, '2023-03-10 09:00:00.000000', '2023-03-10 09:15:00.000000', 10, 'Mesa de Trabajo', 10, 10, 10, 400.25);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Teléfono móvil', 2, true, 11, '2023-04-05 11:45:00.000000', '2023-04-05 12:00:00.000000', 11, 'Teléfono XYZ', 11, 11, 11, 600.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Monitor de pantalla plana', 2, true, 12, '2023-08-14 09:15:00.000000', '2023-10-14 09:30:00.000000', 12, 'Monitor LED', 12, 12, 12, 400.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Cámara digital', 2, true, 13, '2023-08-18 13:45:00.000000', '2023-08-18 14:00:00.000000', 13, 'Cámara DSLR', 13, 13, 13, 700.25);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Computadora portátil', 2, true, 14, '2023-01-15 10:30:00.000000', '2023-01-15 10:45:00.000000', 14, 'Laptop XYZ', 14, 14, 14, 1200.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Proyector multimedia', 2, true, 15, '2023-06-08 15:20:00.000000', '2023-06-08 15:35:00.000000', 15, 'Proyector HD', 15, 15, 15, 900.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Impresora láser', 2, true, 16, '2023-02-20 14:15:00.000000', '2023-02-20 14:30:00.000000', 16, 'Impresora ABC', 16, 16, 16, 800.75);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Escritorio ejecutivo', 2, true, 17, '2023-07-20 10:00:00.000000', '2023-07-20 10:15:00.000000', 17, 'Escritorio Ejecutivo', 17, 17, 17, 350.75);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Silla de oficina', 2, true, 18, '2023-05-12 08:30:00.000000', '2023-05-12 08:45:00.000000', 18, 'Silla Ergonómica', 18, 18, 18, 150.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Aire acondicionado', 2, true, 19, '2023-09-25 12:30:00.000000', '2023-09-25 12:45:00.000000', 19, 'Aire Acondicionado XYZ', 19, 19, 1, 1200.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Mesa de oficina', 2, true, 20, '2023-03-10 09:00:00.000000', '2023-03-10 09:15:00.000000', 20, 'Mesa de Trabajo', 20, 20, 2, 400.25);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Teléfono móvil', 3, true, 21, '2023-04-05 11:45:00.000000', '2023-04-05 12:00:00.000000', 1, 'Teléfono XYZ', 1, 21, 3, 600.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Monitor de pantalla plana', 3, true, 22, '2023-08-14 09:15:00.000000', '2023-10-14 09:30:00.000000', 2, 'Monitor LED', 2, 22, 4, 400.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Cámara digital', 3, true, 23, '2023-08-18 13:45:00.000000', '2023-08-18 14:00:00.000000', 3, 'Cámara DSLR', 3, 23, 5, 700.25);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Computadora portátil', 3, true, 24, '2023-01-15 10:30:00.000000', '2023-01-15 10:45:00.000000', 4, 'Laptop XYZ', 4, 24, 6, 1200.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Proyector multimedia', 3, true, 25, '2023-06-08 15:20:00.000000', '2023-06-08 15:35:00.000000', 5, 'Proyector HD', 5, 25, 7, 900.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Impresora láser', 3, true, 26, '2023-02-20 14:15:00.000000', '2023-02-20 14:30:00.000000', 6, 'Impresora ABC', 6, 26, 8, 800.75);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Escritorio ejecutivo', 3, true, 27, '2023-07-20 10:00:00.000000', '2023-07-20 10:15:00.000000', 7, 'Escritorio Ejecutivo', 7, 27, 9, 350.75);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Silla de oficina', 3, true, 28, '2023-05-12 08:30:00.000000', '2023-05-12 08:45:00.000000', 8, 'Silla Ergonómica', 8, 28, 10, 150.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Aire acondicionado', 3, true, 29, '2023-09-25 12:30:00.000000', '2023-09-25 12:45:00.000000', 9, 'Aire Acondicionado XYZ', 9, 29, 11, 1200.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Mesa de oficina', 3, true, 30, '2023-03-10 09:00:00.000000', '2023-03-10 09:15:00.000000', 10, 'Mesa de Trabajo', 10, 30, 12, 400.25);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Teléfono móvil', 4, true, 31, '2023-04-05 11:45:00.000000', '2023-04-05 12:00:00.000000', 11, 'Teléfono XYZ', 11, 31, 13, 600.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Monitor de pantalla plana', 4, true, 32, '2023-08-14 09:15:00.000000', '2023-10-14 09:30:00.000000', 12, 'Monitor LED', 12, 1, 14, 400.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Cámara digital', 4, true, 33, '2023-08-18 13:45:00.000000', '2023-08-18 14:00:00.000000', 13, 'Cámara DSLR', 13, 2, 15, 700.25);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Computadora portátil', 4, true, 34, '2023-01-15 10:30:00.000000', '2023-01-15 10:45:00.000000', 14, 'Laptop XYZ', 14, 3, 16, 1200.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Proyector multimedia', 4, true, 35, '2023-06-08 15:20:00.000000', '2023-06-08 15:35:00.000000', 15, 'Proyector HD', 15, 4, 17, 900.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Impresora láser', 4, true, 36, '2023-02-20 14:15:00.000000', '2023-02-20 14:30:00.000000', 16, 'Impresora ABC', 16, 5, 18, 800.75);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Escritorio ejecutivo', 4, true, 37, '2023-07-20 10:00:00.000000', '2023-07-20 10:15:00.000000', 17, 'Escritorio Ejecutivo', 17, 6, 11, 350.75);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Silla de oficina', 4, true, 38, '2023-05-12 08:30:00.000000', '2023-05-12 08:45:00.000000', 18, 'Silla Ergonómica', 18, 7, 1, 150.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Aire acondicionado', 4, true, 39, '2023-09-25 12:30:00.000000', '2023-09-25 12:45:00.000000', 19, 'Aire Acondicionado XYZ', 19, 8, 2, 1200.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Mesa de oficina', 4, true, 40, '2023-03-10 09:00:00.000000', '2023-03-10 09:15:00.000000', 20, 'Mesa de Trabajo', 20, 9, 3, 400.25);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Teléfono móvil', 5, true, 1, '2023-04-05 11:45:00.000000', '2023-04-05 12:00:00.000000', 1, 'Teléfono XYZ', 1, 10, 4, 600.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Monitor de pantalla plana', 5, true, 2, '2023-08-14 09:15:00.000000', '2023-10-14 09:30:00.000000', 2, 'Monitor LED', 2, 11, 5, 400.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Cámara digital', 5, true, 3, '2023-08-18 13:45:00.000000', '2023-08-18 14:00:00.000000', 3, 'Cámara DSLR', 3, 12, 6, 700.25);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Computadora portátil', 5, true, 4, '2023-01-15 10:30:00.000000', '2023-01-15 10:45:00.000000', 4, 'Laptop XYZ', 4, 13, 7, 1200.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Proyector multimedia', 5, true, 5, '2023-06-08 15:20:00.000000', '2023-06-08 15:35:00.000000', 5, 'Proyector HD', 5, 14, 8, 900.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Impresora láser', 5, true, 6, '2023-02-20 14:15:00.000000', '2023-02-20 14:30:00.000000', 6, 'Impresora ABC', 6, 15, 9, 800.75);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Escritorio ejecutivo', 5, true, 7, '2023-07-20 10:00:00.000000', '2023-07-20 10:15:00.000000', 7, 'Escritorio Ejecutivo', 7, 16, 10, 350.75);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Silla de oficina', 5, true, 8, '2023-05-12 08:30:00.000000', '2023-05-12 08:45:00.000000', 8, 'Silla Ergonómica', 8, 17, 11, 150.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Aire acondicionado', 5, true, 9, '2023-09-25 12:30:00.000000', '2023-09-25 12:45:00.000000', 9, 'Aire Acondicionado XYZ', 9, 18, 12, 1200.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Mesa de oficina', 5, true, 10, '2023-03-10 09:00:00.000000', '2023-03-10 09:15:00.000000', 10, 'Mesa de Trabajo', 10, 19, 13, 400.25);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Teléfono móvil', 6, true, 11, '2023-04-05 11:45:00.000000', '2023-04-05 12:00:00.000000', 11, 'Teléfono XYZ', 11, 20, 14, 600.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Monitor de pantalla plana', 6, true, 12, '2023-08-14 09:15:00.000000', '2023-10-14 09:30:00.000000', 12, 'Monitor LED', 12, 21, 15, 400.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Cámara digital', 6, true, 13, '2023-08-18 13:45:00.000000', '2023-08-18 14:00:00.000000', 13, 'Cámara DSLR', 13, 22, 16, 700.25);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Computadora portátil', 6, true, 14, '2023-01-15 10:30:00.000000', '2023-01-15 10:45:00.000000', 14, 'Laptop XYZ', 14, 23, 17, 1200.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Proyector multimedia', 6, true, 15, '2023-06-08 15:20:00.000000', '2023-06-08 15:35:00.000000', 15, 'Proyector HD', 15, 24, 18, 900.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Impresora láser', 6, true, 16, '2023-02-20 14:15:00.000000', '2023-02-20 14:30:00.000000', 16, 'Impresora ABC', 16, 25, 11, 800.75);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (1, 'Escritorio ejecutivo', 6, true, 17, '2023-07-20 10:00:00.000000', '2023-07-20 10:15:00.000000', 17, 'Escritorio Ejecutivo', 17, 26, 1, 350.75);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (2, 'Silla de oficina', 6, true, 18, '2023-05-12 08:30:00.000000', '2023-05-12 08:45:00.000000', 18, 'Silla Ergonómica', 18, 27, 2, 150.50);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (3, 'Aire acondicionado', 6, true, 19, '2023-09-25 12:30:00.000000', '2023-09-25 12:45:00.000000', 19, 'Aire Acondicionado XYZ', 19, 28, 3, 1200.00);
INSERT INTO public.activo_fijo (condicion_id,descripcion, empresa_id, estado, estado_id, fecha_compra, fecha_registro, marca_id, nombre, personal_id, tipo_activo_id, ubicacion_id, valor) VALUES (4, 'Mesa de oficina', 6, true, 20, '2023-03-10 09:00:00.000000', '2023-03-10 09:15:00.000000', 20, 'Mesa de Trabajo', 20, 29, 4, 400.25);
