POST http://localhost:1234/api/v1/activos-fijos/registrar?nombre=Pantalla8k&valor=900&fechaCompra=19/09/2023&descripcion=LG50&tipoActivoId=1&marcaId=2&calle=Calle%20Principal&avenida=Avenida%20Central&bloqueId=3&ciudadId=4&personalId=1&estadoId=1&condicionId=1&estado=true
###
POST http://localhost:1234/api/v1/activos-fijos/registrar?nombre=Laptop8k&valor=500&fechaCompra=Wed%20Oct%2004%202023&descripcion=LG200&tipoActivoId=1&marcaId=2&calle=Calle%20Principal&avenida=Avenida%20Central&bloqueId=3&ciudadId=4&personalId=1&estadoId=1&condicionId=1&estado=true&idEmp=1
###
POST http://localhost:1234/api/v1/activos-fijos/excel?nombreArchivo=activosFijos.xlsx
Content-Type: application/json

[
  {
    "id": 1,
    "nombre": "Activo 1",
    "valor": 100.0,
    "fechaCompra": "2023-10-26",
    "descripcion": "Descripción 1",
    "tipoActivoNombre": "Tipo 1",
    "personalNombre": "Personal 1",
    "ciudadNombre": "La Paz",
    "bloqueNombre": "Bloque 1",
    "avenida": "Avenida 1",
    "calle": "Calle 1",
    "condicionNombre": "Condición 1",
    "estadoNombre": "Estado 1",
    "marcaNombre": "Marca 1",
    "porcentajeDepreciacion": 10,
    "valorDepreciacion": 10.0,
    "valorActual": 90.0
  },
  {
    "id": 2,
    "nombre": "Activo 2",
    "valor": 200.0,
    "fechaCompra": "2023-10-26",
    "descripcion": "Descripción 2",
    "tipoActivoNombre": "Tipo 2",
    "personalNombre": "Personal 1",
    "ciudadNombre": "La Paz",
    "bloqueNombre": "Bloque 1",
    "avenida": "Avenida 1",
    "calle": "Calle 1",
    "condicionNombre": "Condición 1",
    "estadoNombre": "Estado 1",
    "marcaNombre": "Marca 2",
    "porcentajeDepreciacion": 15,
    "valorDepreciacion": 30.0,
    "valorActual": 170.0
  }
]
###
###
POST http://localhost:1234/api/v1/activos-fijos/pdf?nombreArchivo=activosFijos2.pdf&imageUrl=logo.png&username=JuanPerez&empresa=EmpresaSRL
Content-Type: application/json

[
  {
    "id": 1,
    "nombre": "Activo 1",
    "valor": 100.0,
    "fechaCompra": "2023-10-26",
    "descripcion": "Descripción 1",
    "tipoActivoNombre": "Tipo 1",
    "personalNombre": "Personal 1",
    "ciudadNombre": "La Paz",
    "bloqueNombre": "Bloque 1",
    "avenida": "Avenida 1",
    "calle": "Calle 1",
    "condicionNombre": "Condición 1",
    "estadoNombre": "Estado 1",
    "marcaNombre": "Marca 1",
    "porcentajeDepreciacion": 10,
    "valorDepreciacion": 10.0,
    "valorActual": 90.0,
    "mesesRestantes": 48
  },
  {
    "id": 2,
    "nombre": "Activo 2",
    "valor": 200.0,
    "fechaCompra": "2023-10-26",
    "descripcion": "Descripción 2",
    "tipoActivoNombre": "Tipo 2",
    "personalNombre": "Personal 1",
    "ciudadNombre": "La Paz",
    "bloqueNombre": "Bloque 1",
    "avenida": "Avenida 1",
    "calle": "Calle 1",
    "condicionNombre": "Condición 1",
    "estadoNombre": "Estado 1",
    "marcaNombre": "Marca 2",
    "porcentajeDepreciacion": 15,
    "valorDepreciacion": 30.0,
    "valorActual": 170.0,
    "mesesRestantes": 32
  }
]
###
###
GET http://localhost:1234/api/v1/activos-fijos/list
###
GET http://localhost:1234/api/v1/activos-fijos/actF?mes=JANUARY&anio=2028&idEmp=1&username=juan.perez
###
GET http://localhost:1234/api/v1/activos-fijos/actF2?idEmp=1
###
GET http://localhost:1234/api/v1/activos-fijos/cond
###
GET http://localhost:1234/api/v1/activos-fijos/estado?idEmp=2
###
GET http://localhost:1234/api/v1/activos-fijos/ubicacion
###
GET http://localhost:1234/api/v1/activos-fijos/marca
###
GET http://localhost:1234/api/v1/activos-fijos/tipo
###
GET http://localhost:1234/api/v1/activos-fijos/personal?idEmp=1
###
GET http://localhost:1234/api/v1/activos-fijos/bloque?idEmp=3
###
GET http://localhost:1234/api/v1/activos-fijos/ciudad?idEmp=3
###
GET http://localhost:1234/api/v1/activos-fijos/empresas
###
DELETE http://localhost:1234/api/v1/activos-fijos/eliminar/1
###
GET http://localhost:1234/api/v1/activos-fijos/obtener/1
###
PUT http://localhost:1234/api/v1/activos-fijos/actualizar/35?nombre=Activo5%20Actualizado3&valor=6900&fechaCompra=Wed%20Oct%2027%202023&descripcion=Descripción%20Actualizada3&tipoActivoId=2&marcaId=3&calle=Calle%20Nueva&avenida=Avenida%20Nueva&bloqueId=4&ciudadId=5&personalId=3&estadoId=3&condicionId=3&estado=true&username=juan.perez
###
PUT http://localhost:1234/api/v1/activos-fijos/disable?id=10&username=juan.perez
###
                        Activo fijo Historico
###
GET http://localhost:1234/api/v1/activos-fijos-H/actFH
###
GET http://localhost:1234/api/v1/activos-fijos-H/actFHEmpresa?idEmp=1

                        Usuarios
###
POST http://localhost:1234/api/v1/usuarios/login?user=juan.perez&password=1234&empId=2
###
POST http://localhost:1234/api/v1/usuarios/registrar?nombre=Juan&username=juan.perez&password=1234&idRol=1&idEmpresa=1&estado=true
###
POST http://localhost:1234/api/v1/usuarios/registrar?nombre=Juan&username=juan.luis&password=1234&idRol=2&idEmpresa=2&estado=true
###
GET http://localhost:1234/api/v1/usuarios/rol
###
GET http://localhost:1234/api/v1/usuarios/listaUsuario?idEmp=2
###
GET http://localhost:1234/api/v1/usuarios/empresa
###
PUT http://localhost:1234/api/v1/usuarios/actualizar/1?nombre=Juan&username=juan.pablo&password=1234&idRol=1
###
                         Activo fijo depreciado
###
GET http://localhost:1234/api/v1/depreciados/actD?idEmp=1&idTie=25
###
GET http://localhost:1234/api/v1/depreciados/tiempo?idEmp=1
###


